name: QpiBot CI

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag kibnerk/qpibot
      - name: Push the Docker Image
        run: docker push kibnerk/qpibot
