name: QpiBot CI

on:
  push:
    branches: [action]
  pull_request:
    branches: [action]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag kibnerk/qpibot
      - name: Push the Docker Image
        run: docker push kibnerk/qpibot
      - name: run docker file
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/kibnerk.ru/node/qpibot & sudo docker pull kibnerk/qpibot & sudo docker run --env-file .env -p 49164:3000 kibnerk/qpibot
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
