name: QpiBot CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update & restart
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.SERVER_PATH }}
            git pull
            sudo docker-compose up -d --build
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
